[package]
name = "hovinen"
version = "0.1.0"
edition = "2021"

# Hi there!

[dependencies]
dashmap = "6.1.0"
io-uring = "0.7.2"
tokio = { version = "1.42.0", features = ["full"] }

[dev-dependencies]
googletest = "0.11.0"
tempfile = "3.14.0"
